[config]
#原始视频路径
VIDEO_PATH=D:\video-obfuscation\uploads\1778504045_0422Result.avi
#裁切影像路径
SAVE_PATH=D:\video-obfuscation\uploads\VideoCut4Img/
#待组装影像路径
IMG_PATH=D:\video-obfuscation\uploads\VideoCut4Img/
#已组装影像路径
IMG_VIDEO_PATH=D:\video-obfuscation\uploads
