[config]
#原始视频路径
VIDEO_PATH=F:/H_partTime/0002_projectInfo/0422/VideoObfuscation/0422.mp4
#裁切影像路径
SAVE_PATH=F:/H_partTime/0002_projectInfo/0422/VideoObfuscation/VideoCut4Img/
#待组装影像路径
IMG_PATH=F:/H_partTime/0002_projectInfo/0422/VideoObfuscation/VideoCut4Img/
#已组装影像路径
IMG_VIDEO_PATH=F:/H_partTime/0002_projectInfo/0422/VideoObfuscation